### ISSUE TITLE
Example for usage for Jupyter Extensions

### ISSUE THREAD

**Issue by N-Coder** [spoorn/poeblix#1]
I don't really know which files need to be installed where for jupyter extensions to work (I'm currently using the pretty intransparent "magically working" build via [jupyter-packaging](https://github.com/jupyter/jupyter-packaging/)), so could you please include an example configuration for this use-case?

**Comment by spoorn** [comment]
The data_files example in the README is to mimic the behavior of [data_files in setup.py](https://docs.python.org/3/distutils/setupscript.html#installing-additional-files)

This is simply for copying certain data files to a path relative to the \<installation-prefix\>, meaning when you build your package using `poetry blixbuild` and you specify some `data_files` in your `pyproject.toml`, whenever you install the package via the wheel, or through `pip install`, it will also install those data_files into the installation prefix ([installation prefix is sys.prefix or site.USER_BASE](https://docs.python.org/3/distutils/setupscript.html#installing-additional-files))

For example, if my pyproject had this:

```toml
...
[tool.blix.data]
data_files = [
    { destination = "share/data/", from = [ "data_files/test.txt", "data_files/anotherfile" ] },
    { destination = "share/data/threes", from = [ "data_files/athirdfile" ] }
]
...
```

And I'm working on a virtual env at: `~/.virtualenv/myenv`

I can create the wheel file and include those data_files using `poetry blixbuild`

Then install the package from the wheel `pip install <my-newly-built-wheel-file>`.

The install would generate files at:

1. `~/.virtualenv/myenv/share/data/test.txt`
2. `~/.virtualenv/myenv/share/data/anotherfile`
3. `~/.virtualenv/myenv/share/data/threes/athirdfile`


-----

So depending on what jupyter extension you are using, or whatever use case you need, you can generate required files using the `data_files` config.

An example could be [nbconvert templates](https://nbconvert.readthedocs.io/en/latest/customizing.html#where-are-nbconvert-templates-installed).  nbconvert uses templates in directory `<installation prefix>/share/jupyter/nbconvert`, so if your package needed to generate some nbconvert templates, you could include data_files such that when someone installs your package, it installs your nbconvert templates into that directory, and nbconvert will pick them up:

```
[tool.blix.data]
data_files = [
    { destination = "share/jupyter/nbconvert", from = [ "mytemplates/template1.html.j2", "mytemplates/template2.html.j2" ] }
]
...
```

-----

data_files gives flexibility and support for installing any sort of support of arbitrary files in relative arbitrary directories from the \<installation-prefix\>, when your package is installed.  It's not something specific for jupyter extensions.

**Comment by N-Coder** [comment]
Thanks for the info! I'm working on a custom Widget and was wondering which data files need to go where (i.e. which exact values/files to specify in the `data_files` config) and was hoping you already knew the answer for that, but it seems I need to [figure that out](https://github.com/jupyterlab/extension-examples/blob/master/widgets/setup.py#L74) on my own. :sweat_smile:

**Comment by spoorn** [comment]
@N-Coder I see that file has an example path for the data_files if that helps: https://github.com/jupyterlab/extension-examples/blob/master/widgets/setup.py#L25-L28

`destination` in data_files should be those paths, and then `from` is for the local files you have to copy to those paths
