### ISSUE TITLE
Destination path in data_files is absolute

### ISSUE THREAD

**Issue by allstrive** [spoorn/poeblix#12]
I have a config that looks like this 
```
[tool.blix.data]
data_files = [
    { destination = "/etc/jupyter/jupyter_server_config.d/", from = [ "jupyter-config/jupyter_server_config.d/jupyter_workspace_extensions.json" ] },
]
```

When I run `poetry blixbuild` I get the error
```
Destination path in data_files [/etc/jupyter/jupyter_server_config.d/] is absolute.  Please change it to a relative path
```

I need to copy the config file to /etc , which will always be absolute path, how do I achieve capability using this plugin ?

**Comment by spoorn** [comment]
Absolute paths aren't supported for data_files.  This isn't specific to poeblix.  There's a long thread related to this for wheel: https://github.com/pypa/wheel/issues/92

And the same limitations are there with setup.py: https://docs.python.org/3/distutils/setupscript.html#installing-additional-files
