### ISSUE TITLE
Dependency with source parameter

### ISSUE THREAD

**Issue by mateuszlukaszuk** [spoorn/poeblix#19]
I've been working with a project that uses `poetry` (1.6.1) as package manager. We have defined two package sources in `pyproject.toml`:

`[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = source_name
url = my_pypi_url
priority = "default"`

As we want to keep all dependencies' versions in wheel from a lockfile, we decide to use `poeblix` (0.10.0). I want to run `poetry blixbuild --only-lock`, but console tells me that my `source_name` repository doesn't exist. I debugged this issue and it seems that if dependency has `source` parameter passed, then `blixbuild` is failing. The situation doesn't occur when use `poetry build`. 

When I removed `source` from package dependency definition, build has passed.

Do you know about this issue or have plan to fix it?

![sources](https://github.com/spoorn/poeblix/assets/60702974/3196b442-af03-46b5-b9bf-77bf2155fa23)

**Comment by khab-el** [comment]
just change line https://github.com/spoorn/poeblix/blob/main/src/poeblix/util/util.py#L30 to that:
`pool = RepositoryPool(repositories=poetry._pool.all_repositories, ignore_repository_names=True)`
