### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by Caetan95** [spoorn/poeblix#2]
Hello :smile:  

First of all thanks for the plugin! I was wondering if it could be compatible with Python 3.8

Thanks!

**Comment by spoorn** [comment]
Added in https://github.com/spoorn/poeblix/commit/0a17cbbb0ff4c2eb8572d8827930726836e83814

Should be available now: https://pypi.org/project/poeblix/0.3.1/, https://github.com/spoorn/poeblix/releases/tag/0.3.1
