### ISSUE TITLE
Error using poetry@1.2.0b3

### ISSUE THREAD

**Issue by Caetan95** [spoorn/poeblix#3]
Hello,

running `poetry blixbuild` breaks and doesn't work with the latest version of poetry (poetry@1.2.0b3)

```
[tool.blix.data] section not found in /build/pyproject.toml, no data_files to process
__init__() missing 1 required positional argument: 'name'
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

Cheers

**Comment by spoorn** [comment]
Ah, the test updates poetry in the environment, but not the virtualenv where the test is ran

**Comment by spoorn** [comment]
Released poeblix 0.4.0

https://pypi.org/project/poeblix/

https://github.com/spoorn/poeblix/releases/tag/0.4.0

Let me know if there are still issues

**Comment by Caetan95** [comment]
Works perfect, thanks!!

**Comment by Caetan95** [comment]
Hello,

I reopen this issue due to the recent update to v0.5.2, which seems that it's not supported for poetry 1.2.0b3

```
Using version ^0.5.2 for poeblix
Updating dependencies
Resolving dependencies...
Because no versions of poeblix match >0.5.2,<0.6.0
 and poeblix (0.5.2) depends on poetry (>=1.2.0rc1,<2.0), poeblix (>=0.5.2,<0.6.0) requires poetry (>=1.2.0rc1,<2.0).
So, because poetry-instance depends on both poetry (1.2.0b3) and poeblix (^0.5.2), version solving failed.
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

Do you plan to support it?

**Comment by spoorn** [comment]
@Caetan95 I believe 0.5.0 should work for 1.2.0b3, if you're still on that version of poetry, you could try pinning poeblix to that version

**Comment by Caetan95** [comment]
It seems to work, thanks!
