### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by sduenas** [spoorn/poeblix#5]
I've noticed your project doesn't have a license. By default, that means nobody can use/copy/distribute your software without your permission. 
I suggest you should add one LICENSE, probably a free/open source license, so everybody can benefit from that. If you are not sure which one choose, I recommend to use the same one that is used by poetry - I think it's MIT - so there are no incompatibilities when people use it or package with your project.

**Comment by spoorn** [comment]
Done https://github.com/spoorn/poeblix/blob/main/LICENSE
