### ISSUE TITLE
Using --only-lock removes extras information

### ISSUE THREAD

**Issue by DrManac** [spoorn/poeblix#8]
When package has optional extra dependencies

    [tool.poetry.dependencies]
    gunicorn = { version = "^19.9.0", optional = true }
    [tool.poetry.extras]
    gunicorn = ["gunicorn"]

the default build step produces correct metadata

    Provides-Extra: gunicorn
    Requires-Dist: gunicorn (>=19.9.0,<20.0.0); extra == "gunicorn"

When building with **--only-lock** flag the extra information is missing

    Provides-Extra: gunicorn
    Requires-Dist: gunicorn (==19.10.0)

**Comment by spoorn** [comment]
Fixed in 0.6.0
