### ISSUE TITLE
`poetry plugin add` doesn't work with poetry > 1.3.2

### ISSUE THREAD

**Issue by faxm0dem** [spoorn/poeblix#9]
When using the `poetry plugin add poeblix` command on poetry 1.3.2 I get:

```
☠ poetry plugin add poeblix

The command "plugin" does not exist.

Did you mean this?
    self show plugins
```

It would seem the [right](https://python-poetry.org/docs/master/plugins/#the-self-add-command) way to do it is the following : 

```
poetry self add poeblix
```

**Comment by spoorn** [comment]
Fixed in https://github.com/spoorn/poeblix/commit/058ffeac94f9dcd716435128e4c503bbd837ceb0
